name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cpp-tests:
    uses: ./.github/workflows/setup.yml
    with:
      install-dev-deps: true
      python-version: '3.8'
    
  python-tests:
    uses: ./.github/workflows/setup.yml
    with:
      python-version: '3.9'
      install-dev-deps: true
    
  benchmarks:
    uses: ./.github/workflows/setup.yml
    with:
      install-dev-deps: false