name: Reusable Setup Workflow

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.8'
      install-dev-deps:
        type: boolean
        default: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pybind11[global]"
          pip install -r requirements.txt
          
          if [ "${{ inputs.install-dev-deps }}" = "true" ]; then
            pip install pybind11 numpy coverage
          fi
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake lcov